//PAGE PRINCIPALE//

GET http://localhost:3000/
// Renvoie la page principale
###
// ACTIVITES ROUTES //

GET http://localhost:3000/activities
// Renvoie les informations de toutes les activités
###
GET http://localhost:3000/activities/1
//Renvoie les informations d'une activité
###
POST http://localhost:3000/activities/add
// Crée une activité et la lie à un animateur
Content-Type: application/json

{"sportName": "football", "sportDesc": "football en salle", "placeID":  1}
###
GET http://localhost:3000/activities/delete/5
// Supprime une activité
###
POST http://localhost:3000/activities/update/1
//Met à jour les informations d'une activité
Content-Type: application/json

{"sportName": "hockey", "sportDesc": "hockey sur glace", "placeID":  1}
###
//POST http://localhost:3000/inscription/activities
// Envoie son inscription à une activité
###
//GET http://localhost:3000/activities/:userResponsable
//Renvoie les informations des activités proposées par un responsable
###
// UTILISATEURS ROUTES //

GET http://localhost:3000/users
// Renvoie la liste des utilisateurs enregistrés et leurs infos
###
GET http://localhost:3000/users/:userId
// Renvoie la liste des utilisateurs enregistrés et leurs infos
###
GET http://localhost:3000/users/delete/2
// Supprime l'utilisateur et ses infos
###
POST http://localhost:3000/users/add
// Ajoute un utilisateur et ses infos
Content-Type: application/json

{"userName":"antoine", "userLastName":"Geonet", "mailAdd":"a@a.a", "password": "voiture",
  "rue":"chemin du corbeau","numero":4,"codepost":1300,"villenom": "wavre","droitID":1}
###
POST http://localhost:3000/users/update/1
// Met à jour les infos d'un utilisateur
Content-Type: application/json

{"userName":"quentin", "userLastName":"roeland", "mailAdd":"a@a.a", "password": "voiture", "addressID": 1,
  "rue":"chemin du corbeau","numero":4,"codepost":1000,"villenom": "bruxelles", "oldCodepost": 1000}
###
POST http://localhost:3000/users/rights/1
// Met à jour les droits d'un utilisateur
Content-Type: application/json

{"droitID": 1}
###
// LOGIN ROUTES //

POST http://localhost:3000/login
// Renvoie la page de login
